### ISSUE TITLE
Indigo renderer still shows up in f3

### ISSUE THREAD

**Issue by Jason103J** [LoganDark/fabric-branding#3] opened 2021-06-25 05:56 UTC
![image](https://user-images.githubusercontent.com/71662501/123376313-48ca7c00-d558-11eb-8760-2080cad270b1.png)
is there a way to remove this?

**Comment by LoganDark** [comment] 2021-06-25 05:58
That text is added by Fabric API. Most mods depend on Fabric API, however, so if you remove it some mods may stop working. If you don't want that visible, you can't use any mods that require Fabric API.

The Branding mod is not designed to protect you against screensharing, so I'm closing this as intended behavior.

**Closed as completed by LoganDark** 2021-06-25 05:58 UTC

**Comment by Kichura** [comment] 2021-06-27 12:16
Commenting on this in case others wanna attempt this with a dummy copy of fabric api: The debughud context can be removed straight from the rendering jar file (found inside api's meta-inf data) by wiping out the debughud code from refmap, the fabric.mod.json and ofc the folder "debughud" via "net\fabricmc\fabric\mixin\renderer\client" respectively.

(*Although please note that you should not attempt yourself if you lack any knowledge on how to modify jars at all)

Otherwise, there is no way to get rid of that text-string without having to disable the mod entirely (or modify it yourself if you know better) which ofc can result in other mods malfunctioning.

**Comment by LoganDark** [comment] 2021-06-27 12:18
@Kichura The reason I didn't provide any further detail is that I suspect this user might be attempting to survive screensharing (aka cheating in servers while pretending to be a vanilla client). While that is useful info, I don't think this issue was the best place to put it. Just my two cents.
